### PR TITLE
highlight mismatch part of search string like isearch does

### PR DESCRIPTION
**Pull request by lo2net**
Just for fun!

### CODE REVIEW

**Comment by zk-phi** [comment]
cool, thanks!

**Comment by lo2net** [comment]
:+1:

**Comment by knu** [comment]
This is a cool feature, but there's a bug in this implementation.  Try typing "abd?" in phi-search against a buffer containing "abc", you'll see the "d?" part highlighted while the whole pattern has a successful match at "ab".

**Comment by zk-phi** [comment]
it's probably fixed in the last commit.
thanks for the report.

**Comment by lo2net** [comment]
There is another bug: when search with "\(abc\)" in a buffer containing "abc" and use <backspace> to delete char, 'phi-search--fail-pos' will be larger then '(point-max)', result in an error message "Args out of range".
And it looks like phi-search did not save a search history(or state), so after fixing that, which part of search string should be highlighted?

**Comment by zk-phi** [comment]
fixed to set "fail-pos" to the actual position of the modification (not "(1- (point-max))").
in addition fixed to highlight whole query if it's an invalid regexp (like isearch does).

**Comment by lo2net** [comment]
:+1: error fixed.
But search with '"\(abc\)x?"' and then delete char ''?'', ''x'' should be highlighted as failed part:
bug
Am I right?

**Comment by zk-phi** [comment]
thanks. i opened a separate issue.
we probably need something like a search history stack like `isearch-cmds` (in isearch.el), to implement it.

**Pull request merged**
